FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_ADSENSE_CLIENT_ID
ENV NEXT_PUBLIC_ADSENSE_CLIENT_ID=$NEXT_PUBLIC_ADSENSE_CLIENT_ID
ARG NEXT_PUBLIC_CONTACT_EMAIL=
ARG NEXT_PUBLIC_AFFILIATE_ENABLED=false
ARG NEXT_PUBLIC_AFFILIATE_NAME=
ARG NEXT_PUBLIC_AFFILIATE_URL=
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build
FROM nginx:alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/out /usr/share/nginx/html
EXPOSE 3000
